# For Github Pages info see: https://help.github.com/articles/configuring-jekyll/

# Site settings
title: Dylan's Blog
header-img: img/home-bg.jpg
email: dylanhogg at gmail.com
copyright_name: Dylan Hogg
description: "Dylan's Blog: Explorations in AI, Machine Learning and the Future."
baseurl: ""
#url: "http://dylanhogg.github.io"
#url: "http://blog.infocruncher.com.s3-website-us-east-1.amazonaws.com/"
url: "http://blog.infocruncher.com"
twitter_username: dylanhogg
github_username: dylanhogg
linkedin_username: dylanhogg
stackoverflow_username: 249597/dylan-hogg
facebook_username:
email_username:
disqus_shortname: dylanhogg-github-io # TODO: review for 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-5303260-13

# Extra options
timezone: Australia/Sydney
future: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
